const docs={
imovel:[
 {group:'Visão geral',title:'Planta de situação da propriedade',meta:'PDF · 1 página',src:'assets/data-room/imovel/planta-de-situacao.pdf'},
 {group:'Escrituras',title:'Escritura - Área A',meta:'PDF · 2 páginas',src:'assets/data-room/imovel/escritura-area-a.pdf',secondary:true},{group:'Escrituras',title:'Escritura - Áreas J e C',meta:'PDF · 3 páginas',src:'assets/data-room/imovel/escritura-areas-j-c.pdf',secondary:true},{group:'Escrituras',title:'Escritura - Área D',meta:'PDF · 3 páginas',src:'assets/data-room/imovel/escritura-area-d.pdf',secondary:true},
 {group:'Registro e remembramento',title:'Registro de imóvel - Área A',meta:'PDF · 2 páginas',src:'assets/data-room/imovel/registro-area-a.pdf',secondary:true},{group:'Registro e remembramento',title:'Registro de imóvel - Área D',meta:'PDF · 2 páginas',src:'assets/data-room/imovel/registro-area-d.pdf',secondary:true},{group:'Registro e remembramento',title:'Registro de imóvel - Áreas J e C',meta:'PDF · 2 páginas',src:'assets/data-room/imovel/registro-areas-j-c.pdf',secondary:true},{group:'Registro e remembramento',title:'Certidão de remembramento - Página 01',meta:'Imagem · JPEG',src:'assets/data-room/imovel/certidao-remembramento-01.jpeg',type:'image',secondary:true},{group:'Registro e remembramento',title:'Certidão de remembramento - Página 02',meta:'Imagem · JPEG',src:'assets/data-room/imovel/certidao-remembramento-02.jpeg',type:'image',secondary:true},
 ...Array.from({length:8},(_,i)=>({group:'Projetos e averbações',title:`Projeto original - Planta ${String(i+1).padStart(2,'0')} de 08`,meta:'PDF · 1 página',src:`assets/data-room/imovel/projeto-original-${String(i+1).padStart(2,'0')}.pdf`})),
 {group:'Projetos e averbações',title:'Certidão de averbação da obra',meta:'PDF · 1 página',src:'assets/data-room/imovel/certidao-averbacao-obra.pdf',secondary:true},{group:'Projetos e averbações',title:'Ampliação de 15 suítes - Prancha 01 de 02',meta:'Imagem · JPEG',src:'assets/data-room/imovel/ampliacao-15-suites-01.jpeg',type:'image'},{group:'Projetos e averbações',title:'Ampliação de 15 suítes - Prancha 02 de 02',meta:'Imagem · JPEG',src:'assets/data-room/imovel/ampliacao-15-suites-02.jpeg',type:'image'},
 {group:'Avaliação',title:'Avaliação mercadológica do imóvel',meta:'PDF · 11 páginas',src:'assets/data-room/imovel/avaliacao-mercadologica.pdf',secondary:true}
],
historia:[
 {group:'Contenção e implantação',title:'Planta de contenção 01',meta:'PDF · 1 página',src:'assets/data-room/historia/contencao-01.pdf'},{group:'Contenção e implantação',title:'Planta de contenção e situação 02',meta:'PDF · 1 página',src:'assets/data-room/historia/contencao-02.pdf'},
 {group:'Centro acústico',title:'Estúdio - Planta geral 001/025',meta:'Imagem · WEBP',src:'assets/data-room/historia/estudio-planta-001.webp',type:'image'},{group:'Centro acústico',title:'Estúdio A',meta:'PDF · 1 página',src:'assets/data-room/historia/estudio-a.pdf'},{group:'Centro acústico',title:'Estúdio C - Planta',meta:'PDF · 1 página',src:'assets/data-room/historia/estudio-c.pdf'},{group:'Centro acústico',title:'Estúdio B - Render A3',meta:'PDF · 1 página',src:'assets/data-room/historia/estudio-b-render.pdf'},{group:'Centro acústico',title:'Estúdio - Técnica R',meta:'PDF · 1 página',src:'assets/data-room/historia/estudio-tecnica-r.pdf'},{group:'Centro acústico',title:'Estúdio - Montanha',meta:'PDF · 10 páginas',src:'assets/data-room/historia/estudio-montanha.pdf'},
 {group:'Laudos',title:'Laudo técnico do imóvel - Arq. Newton',meta:'PDF · 3 páginas',src:'assets/data-room/historia/laudo-tecnico-imovel.pdf'},{group:'Laudos',title:'Relatório 3596 - Qualidade da água',meta:'PDF · 2 páginas',src:'assets/data-room/historia/laudo-qualidade-agua.pdf'},{group:'Laudos',title:'Certificado de segurança contra incêndio',meta:'PDF · 1 página',src:'assets/data-room/historia/certificado-corpo-bombeiros.pdf'}
],
financeiro:[
 {group:'Contexto',title:'Carta de apresentação dos demonstrativos',meta:'PDF · 2 páginas',src:'assets/data-room/financeiro/carta-apresentacao-demonstrativos.pdf',secondary:true},
 ...[2025,2026,2027].map(year=>({group:'Espaço Regênesis',title:`DRE Espaço Regênesis - ${year}`,meta:'PDF · 3 páginas',src:`assets/data-room/financeiro/dre-regenesis-${year}.pdf`,secondary:true})),
 ...[2025,2026,2027].map(year=>({group:'Emagre Spa',title:`DRE Emagre Spa - ${year}`,meta:'PDF · 3 páginas',src:`assets/data-room/financeiro/dre-emagre-${year}.pdf`,secondary:true}))
]};
const unlocked=new URLSearchParams(location.search).get('secondary')==='unlocked';const viewer=document.querySelector('#document-viewer'),body=document.querySelector('.viewer-body'),title=document.querySelector('#viewer-title'),level=document.querySelector('#viewer-level');let lastTrigger=null;
Object.entries(docs).forEach(([category,items])=>{const root=document.querySelector(`[data-category="${category}"]`);if(!root)return;const groups=[...new Set(items.map(d=>d.group))];groups.forEach(group=>{const section=document.createElement('section');section.className='doc-group';const h=document.createElement('h3');h.textContent=group;const list=document.createElement('div');list.className='doc-list';items.filter(d=>d.group===group).forEach(doc=>{const button=document.createElement('button');button.type='button';button.className=`doc-card${doc.secondary?' secondary':''}`;button.dataset.search=`${doc.title} ${doc.group}`.toLowerCase();button.innerHTML=`<strong>${doc.title}</strong><span>${doc.meta}</span><em>${doc.secondary&&!unlocked?'Inserir segunda senha':'Abrir documento'}</em>`;button.addEventListener('click',()=>{if(doc.secondary&&!unlocked){location.href=`/auth/secondary?next=${encodeURIComponent(`/data-room.html?secondary=unlocked#${category}`)}`;return}openDocument(doc,button)});list.append(button)});section.append(h,list);root.append(section)})});
function openDocument(doc,trigger){lastTrigger=trigger;title.textContent=doc.title;level.textContent=doc.secondary?'Proteção adicional autorizada':'Acesso autorizado';body.innerHTML='<p class="viewer-status" role="status">Preparando documento…</p>';viewer.showModal();const el=document.createElement(doc.type==='image'?'img':'iframe');el.title=doc.title;if(doc.type==='image')el.alt=doc.title;el.addEventListener('load',()=>body.replaceChildren(el),{once:true});el.addEventListener('error',()=>body.innerHTML='<p class="viewer-status">Não foi possível abrir este arquivo. Tente novamente ou fale com a equipe.</p>',{once:true});el.src=doc.src}
function closeViewer(){viewer.close();body.replaceChildren();lastTrigger?.focus()}document.querySelector('.viewer-close').addEventListener('click',closeViewer);viewer.addEventListener('cancel',e=>{e.preventDefault();closeViewer()});
document.querySelector('#doc-search').addEventListener('input',e=>{const term=e.target.value.trim().toLowerCase();document.querySelectorAll('.doc-card').forEach(card=>card.hidden=term&&!card.dataset.search.includes(term));document.querySelectorAll('.doc-group').forEach(group=>group.hidden=![...group.querySelectorAll('.doc-card')].some(card=>!card.hidden))});
