const q=(s,c=document)=>c.querySelector(s);const qa=(s,c=document)=>[...c.querySelectorAll(s)];
const menu=q('.menu'),nav=q('#nav');menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});qa('#nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
const progress=q('.progress span');addEventListener('scroll',()=>{const end=q('#contato').offsetTop+q('#contato').offsetHeight-innerHeight;progress.style.width=`${Math.max(0,Math.min(100,scrollY/end*100))}%`},{passive:true});
document.documentElement.classList.add('reveal-ready');const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});qa('.observe').forEach(e=>reveal.observe(e));
const links=qa('#nav a[href^="#"]'),sections=links.map(a=>q(a.hash)).filter(Boolean);const active=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){links.forEach(a=>a.classList.toggle('active',a.hash===`#${e.target.id}`))}}),{rootMargin:'-40% 0px -55%'});sections.forEach(s=>active.observe(s));
function hydrate(video){const source=q('source[data-src]',video);if(source){source.src=source.dataset.src;source.removeAttribute('data-src');video.load()}}
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)'),mobileLayout=matchMedia('(max-width: 700px)');qa('video').forEach(v=>{if(v.controls)v.addEventListener('play',()=>{hydrate(v);qa('.micro-loop').forEach(loop=>loop.pause())},{once:true})});const ambient=q('.ambient-video'),toggle=q('.media-toggle');toggle?.addEventListener('click',async()=>{hydrate(ambient);try{await ambient.play();toggle.hidden=true}catch{}});new IntersectionObserver(([e])=>{if(!e.isIntersecting&&ambient&&!ambient.paused)ambient.pause()},{threshold:.25}).observe(ambient);
const loopObserver=new IntersectionObserver(entries=>entries.forEach(async({target,isIntersecting})=>{if(!isIntersecting){target.pause();return}if(reducedMotion.matches||mobileLayout.matches)return;hydrate(target);try{await target.play()}catch{}}),{rootMargin:'120px 0px',threshold:.35});qa('.micro-loop').forEach(video=>loopObserver.observe(video));
const access=q('#access-dialog'),map=q('#map-dialog');qa('.request-access').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();access.showModal()}));q('.contact-open')?.addEventListener('click',()=>access.showModal());q('.expand-map')?.addEventListener('click',()=>map.showModal());qa('dialog').forEach(d=>{q('.dialog-close',d)?.addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d)d.close()});d.addEventListener('close',()=>document.body.classList.remove('modal-open'))});
const accessForm=q('#access-form');accessForm?.addEventListener('submit',e=>{if(location.hostname==='127.0.0.1'||location.hostname==='localhost'){e.preventDefault();location.href='/data-room.html?secondary=unlocked'}});
addEventListener('keydown',e=>{if(e.key==='Escape')qa('dialog[open]').forEach(d=>d.close())});
