const q=(s,c=document)=>c.querySelector(s);const qa=(s,c=document)=>[...c.querySelectorAll(s)];
window.dataLayer=window.dataLayer||[];
const track=(event,detail={})=>{const payload={event,...detail};window.dataLayer.push(payload);if(navigator.sendBeacon){navigator.sendBeacon('/api/analytics',new Blob([JSON.stringify(payload)],{type:'application/json'}))}else{fetch('/api/analytics',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload),keepalive:true}).catch(()=>{})}};
const menu=q('.menu'),nav=q('#nav');menu?.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});qa('#nav a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu?.setAttribute('aria-expanded','false')}));
const progress=q('.progress span');addEventListener('scroll',()=>{const contactSection=q('#contato'),end=contactSection.offsetTop+contactSection.offsetHeight-innerHeight;progress.style.width=`${Math.max(0,Math.min(100,scrollY/end*100))}%`},{passive:true});
document.documentElement.classList.add('reveal-ready');const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.08});qa('.observe').forEach(e=>reveal.observe(e));
const links=qa('#nav a[href^="#"]'),sections=links.map(a=>q(a.hash)).filter(Boolean);const active=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){links.forEach(a=>a.classList.toggle('active',a.hash===`#${e.target.id}`))}}),{rootMargin:'-40% 0px -55%'});sections.forEach(s=>active.observe(s));
function hydrate(video){const source=q('source[data-src]',video);if(source){source.src=source.dataset.src;source.removeAttribute('data-src');video.load()}}
const reducedMotion=matchMedia('(prefers-reduced-motion: reduce)'),mobileLayout=matchMedia('(max-width: 700px)');const manualVideos=qa('video[controls]');manualVideos.forEach(v=>v.addEventListener('play',()=>{qa('.micro-loop').forEach(loop=>loop.pause())}));const manualVideoObserver=new IntersectionObserver(entries=>entries.forEach(({target,isIntersecting})=>{if(isIntersecting){hydrate(target);manualVideoObserver.unobserve(target)}}),{rootMargin:'200px 0px',threshold:.01});manualVideos.forEach(video=>manualVideoObserver.observe(video));const ambient=q('.ambient-video'),toggle=q('.media-toggle');toggle?.addEventListener('click',async()=>{hydrate(ambient);try{await ambient.play();toggle.hidden=true;track('video_play',{section:'visao-geral'})}catch{}});if(ambient)new IntersectionObserver(([e])=>{if(!e.isIntersecting&&!ambient.paused)ambient.pause()},{threshold:.25}).observe(ambient);
const loopObserver=new IntersectionObserver(entries=>entries.forEach(async({target,isIntersecting})=>{if(!isIntersecting){target.pause();return}if(reducedMotion.matches||mobileLayout.matches)return;hydrate(target);try{await target.play()}catch{}}),{rootMargin:'120px 0px',threshold:.35});qa('.micro-loop').forEach(video=>loopObserver.observe(video));
const access=q('#access-dialog'),contact=q('#contact-dialog'),map=q('#map-dialog'),legal=q('#legal-dialog');let dialogTrigger=null;
function openDialog(dialog,trigger){if(!dialog)return;dialogTrigger=trigger;document.body.classList.add('modal-open');dialog.showModal();requestAnimationFrame(()=>q('input:not([type="hidden"]),select,textarea,button',dialog)?.focus())}
qa('.request-access').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();const next=el.dataset.next||el.getAttribute('href')||'/data-room.html',origin=el.dataset.origin||'site';q('[name="next"]',access).value=next.startsWith('/')?next:`/${next}`;q('[name="origin"]',access).value=origin;q('[name="startedAt"]',access).value=String(Date.now());track('access_request_open',{origin,category:next.split('#')[1]||'index'});openDialog(access,el)}));
qa('.contact-open').forEach(el=>el.addEventListener('click',()=>{const origin=el.dataset.origin||'site';q('[name="origin"]',contact).value=origin;q('[name="startedAt"]',contact).value=String(Date.now());track('contact_open',{origin});openDialog(contact,el)}));
q('.expand-map')?.addEventListener('click',e=>{track('map_expand');openDialog(map,e.currentTarget)});
const legalCopy={privacy:{title:'Política de privacidade',html:'<p>Os dados enviados nos formulários são usados exclusivamente para responder à solicitação, qualificar o interesse e organizar os próximos passos da oportunidade.</p><p>Nome, contato, organização, perfil e mensagem são encaminhados à equipe responsável. Eles não são vendidos nem utilizados para publicidade de terceiros.</p><p>O titular pode solicitar correção ou exclusão pelo mesmo canal de contato utilizado nesta apresentação.</p>'},confidentiality:{title:'Termos de confidencialidade',html:'<p>Esta apresentação possui caráter informativo e reservado. O acesso a documentos adicionais pode depender de qualificação e aceite de instrumentos específicos.</p><p>O conteúdo não constitui oferta pública, promessa de resultado ou substituição da diligência jurídica, técnica, contábil e financeira do interessado.</p><p>Documentos e informações recebidos não devem ser reproduzidos ou encaminhados sem autorização.</p>'}};
qa('.legal-open').forEach(button=>button.addEventListener('click',()=>{const copy=legalCopy[button.dataset.legal];q('#legal-title').textContent=copy.title;q('#legal-content').innerHTML=copy.html;openDialog(legal,button)}));
qa('dialog').forEach(d=>{q('.dialog-close',d)?.addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d)d.close()});d.addEventListener('close',()=>{document.body.classList.remove('modal-open');dialogTrigger?.focus();dialogTrigger=null})});
q('.gallery-toggle')?.addEventListener('click',e=>{const gallery=q('#infra-gallery'),expanded=e.currentTarget.getAttribute('aria-expanded')==='true';gallery.classList.toggle('expanded',!expanded);e.currentTarget.setAttribute('aria-expanded',String(!expanded));e.currentTarget.textContent=expanded?'Ver galeria completa':'Recolher galeria';track('gallery_toggle',{expanded:!expanded})});
qa('video:not(.ambient-video)').forEach(video=>video.addEventListener('play',()=>track('video_play',{section:video.closest('section')?.id||'unknown'}),{once:true}));
async function submitLead(form,eventName){const status=q('.form-status',form),button=q('[type="submit"]',form);status.className='form-status';status.textContent='Enviando…';button.disabled=true;try{const response=await fetch(form.action,{method:'POST',headers:{accept:'application/json'},body:new FormData(form)});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.message||'Não foi possível enviar agora.');status.textContent=result.message||'Solicitação enviada. A equipe entrará em contato.';status.classList.add('success');track(eventName,{origin:q('[name="origin"]',form).value});form.reset()}catch(error){status.textContent=error.message;status.classList.add('error');track(`${eventName}_error`,{origin:q('[name="origin"]',form).value})}finally{button.disabled=false}}
const accessForm=q('#access-form');accessForm?.addEventListener('submit',e=>{e.preventDefault();if(accessForm.reportValidity())submitLead(accessForm,'access_request_success')});const contactForm=q('#contact-form');contactForm?.addEventListener('submit',e=>{e.preventDefault();if(contactForm.reportValidity())submitLead(contactForm,'contact_success')});
addEventListener('keydown',e=>{if(e.key==='Escape')qa('dialog[open]').forEach(d=>d.close())});track('page_view',{path:location.pathname});